### PR TITLE
Request to pull my commits for using SlicerToKiwiExporter on Slicer4 with VTK6  

### PR DESCRIPTION
**Pull request by ayamada0614**
Hi Jc,

 I edited the code to use this exporter on Slicer4 with VTK6.
 Would you pull my commits and update this useful extension to use on Slicer4 current stable release and the trunk version?

 We use this exporter daily for making sure the planning images with KiwiViewer on iPad during every surgical case. Thank you very much to create the great extension and KiwiViewer.
 
 Btw, I put my name as the contributor in the source codes.
 It's up to you to erase my name or put it there.

 Regards,

--Atsushi

### CODE REVIEW

**Comment by jcfr** [comment]
Thanks for your contribution :+1: and also thank you for the nice word :)

**Comment by ayamada0614** [comment]
Thank you very much for your prompt work:)

**Comment by jcfr** [comment]
The extensionsIndex has also been updated so that the update extension will be available for both the nightly version and the latest stable version.

**Comment by ayamada0614** [comment]
Thank you very much, JC.

From the next case, we and the department of surgery in our hospital will use the updated extension.

Regards,

--Atsushi

**Comment by jcfr** [comment]
@ayamada0614 Updated packages are now expected to be available through the extension manager. Let me know if it is not the case.

As a side note, you would you be up to write an article in the kitware source that would explain (from a technical perspective) how you use Slicer and Kiwiviewer ? 
See http://www.kitware.com/media/thesource.html

Ping @bcd123

Thanks
Jc

**Comment by ayamada0614** [comment]
Hi Jc,

Thank you very much for updating the package.
I made sure that it works well.

And, thank you very much for introducing the kitware source.
I would push our group to write the article from a technical perspective.

Regards,

--Atsushi

**Pull request merged**
